export class Tag {
  static TYPE = 0;
  static ASIGN = 1;
  static LT = 2;
  static IF = 3;
  static THEN = 4;
  static END = 5;
  static PRODUCT = 6;
  static PLUS = 8;
  static MINUS = 9;
  static DIVISION = 10;
  static LP = 11;
  static RP = 12;
  static EOF = 13;
  static ERROR = 14;
  static ID = 15;
  static NUM = 16;
  static TRUE = 17;
  static FALSE = 18;
  static PRINT = 19;
  static AND = 20;
}